#!/usr/bin/env bash
# Thread-pool characterization benchmark (follow-up work item 2).
#
# Runs the `bench-threads` binary (always built ReleaseFast by build.zig) over
# one or more spots at 1/2/4/8 threads, measuring wall AND CPU time for the
# solve, exploitability, and output passes. The CPU/wall ratio ("cores_busy")
# exposes the persistent pool's busy-spin waste: a serial phase that pins N
# cores for no speedup is pure overhead a spin-then-park pool would reclaim.
#
# Usage:
#   bench/run_thread_bench.sh [spot.toml ...]
# With no args it runs the three physical-runout texture spots (rainbow,
# two-tone, monotone) that match the documented baseline. Each spot takes a few
# minutes on the full physical runout space; pass a single spot to go faster.
#
# Per-spot outputs land in bench/out/threads/:
#   <spot>.json   machine-readable results (read this back into the README)
#   <spot>.txt    the human-readable table
# A combined bench/out/threads/summary.md digests all spots.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT/bench/out/threads"
mkdir -p "$OUT_DIR"

if [ "$#" -gt 0 ]; then
    SPOTS=("$@")
else
    SPOTS=(
        "$ROOT/bench/spots/1_srp_dry.toml"
        "$ROOT/bench/spots/2_srp_twotone.toml"
        "$ROOT/bench/spots/3_srp_monotone.toml"
    )
fi

SUMMARY="$OUT_DIR/summary.md"
{
    echo "# Zolver thread-pool benchmark"
    echo
    echo "Wall + CPU time per phase at 1/2/4/8 threads. \`cores_busy\` = CPU time /"
    echo "wall time (average cores kept busy, spinning included). Generated by"
    echo "\`bench/run_thread_bench.sh\`; git \`$(git -C "$ROOT" rev-parse --short HEAD)\`,"
    echo "\`$(zig version)\`, $(nproc) logical CPUs."
    echo
} > "$SUMMARY"

for spot in "${SPOTS[@]}"; do
    name="$(basename "${spot%.toml}")"
    echo "=== $name ==="
    json="$OUT_DIR/$name.json"
    txt="$OUT_DIR/$name.txt"
    # build.zig forwards everything after `--` to the binary; stdout is JSON,
    # stderr is the live table.
    zig build bench-threads -- "$spot" > "$json" 2> "$txt"
    cat "$txt"
    {
        echo "## $name"
        echo
        echo '```'
        cat "$txt"
        echo '```'
        echo
    } >> "$SUMMARY"
done

echo
echo "wrote per-spot JSON + tables to $OUT_DIR"
echo "combined digest: $SUMMARY"
